server: "mobile-hub.lambdatest.com"
user: "LT_USERNAME"  #Add your LambdaTest username here
key: "LT_ACCESS_KEY"  #Add your LambdaTest accessKey here

common_caps:
  "build": "RSpec Parallel"
  "visual": false
  "network": false
  "console": false
  "w3c": true
  "autoGrantPermissions": true
  "autoAcceptAlerts": true

browser_caps:
  -
    "isRealMobile": "true"
    "platform": "Android"
    "deviceName": "Pixel 5"
    "platformVersion": "11"
    "app": "lt://APP10160301691747362768822447"
  -
    "isRealMobile": "true"
    "platform": "Android"
    "deviceName": "Galaxy S21"
    "platformVersion": "12"
    "app": "lt://APP10160301691747362768822447"

